### ISSUE TITLE
Regression: CSS output differs from Less.js for mixin selector

### ISSUE THREAD

**Issue by fuf13** [wikimedia/less.php#108]
Version: 4.2.0+

### Description
A CSS class used as a mixin that has an extra definition with an attribute selector will cause all properties to be merged at the point of use of the mixin. See example below.
This behavior is unexpected and is different from the JS version.
In version 4.1.1, the behaviour was correct.

### Source LESS code
``` less
.btn {
   color: blue;
   font-weight: bold;

   &[title] {
      background: lightgreen;
   }
}
.btn[disabled] {
   cursor: not-allowed;
   color: red;
}
.btn[test] {
   background-color: pink;
}

.btn-specific {
   .btn();
}
```

### Current CSS output (version 4.2.0+)
``` css
.btn {
   color: blue;
   font-weight: bold;
} 
.btn[title] {
   background: lightgreen;
} 
.btn[disabled] {
   cursor: not-allowed;
   color: red;
} 
.btn[test] {
   background-color: pink;
} 
.btn-specific {
   color: blue;
   font-weight: bold;
   cursor: not-allowed;
   color: red;
   background-color: pink;
} 
.btn-specific[title] {
   background: lightgreen;
}
``` 

### Expected CSS output
``` css
.btn {
   color: blue;
   font-weight: bold;
} 
.btn[title] {
   background: lightgreen;
} 
.btn[disabled] {
   cursor: not-allowed;
   color: red;
} 
.btn[test] {
   background-color: pink;
} 
.btn-specific {
   color: blue;
   font-weight: bold;
}
.btn-specific[title] {
   background: lightgreen;
}
```
