### ISSUE TITLE
Support css @layer notation

### ISSUE THREAD

**Issue by manuel-hegner** [wikimedia/less.php#127]
The css `@layer` syntax is supported by all major browser for some time now. Sadly in less.php it produces an error
```
Less_Exception_Chunk: ParseError: Unexpected input in layers.less on line 1, column 7
1| @layer base, patch, template-styles;
```

**Comment by Krinkle** [comment]
@manuel-hegner Which version of Less.php are you using and what is inside the input file?

Using the example from <https://developer.mozilla.org/en-US/docs/Web/CSS/@layer> this appears to work on Less.php 5.1.0, 5.2.0, 5.2.2, and latest master:

```css
// example.less
@layer module, state;

@layer state {
	.alert {
		background-color: brown;
	}
	p {
		border: medium solid limegreen;
	}
}

@layer module {
	.alert {
		border: medium solid violet;
		background-color: yellow;
		color: white;
	}
}
```
```shell
$ bin/lessc example.less
@layer module, state;
@layer state {
  .alert {
    background-color: brown;
  }
  p {
    border: medium solid limegreen;
  }
}
@layer module {
  .alert {
    border: medium solid violet;
    background-color: yellow;
    color: white;
  }
}
```

If you can reproduce an error on the latest Less.php, try it also in Less.js upstream at <https://lesscss.org/less-preview/> to determine whether it is an upstream bug in the spec, or a bug in our port.
