### ISSUE TITLE
ParseError with variable interpolation after ':' in selector

### ISSUE THREAD

**Issue by plumbojumbo** [wikimedia/less.php#52]
This succeeds:

```php
(new Less_Parser())->parse('@position: after; .@{position} {}');
```

This, however, fails:

```php
(new Less_Parser())->parse('@position: after; &:@{position} {}');
```

```
ParseError: Unexpected input in anonymous-file-2.less on line 1, column 14
1| @foo: after; &:@{foo} {}
```

Both Less.js and lessphp compile it just fine. ([cmp.](https://leafo.net/lessphp/editor.html#%40foo%3A%20after%3B%0A.%40%7Bfoo%7D%20%7B%7D%0A%26%3A%40%7Bfoo%7D%20%7B%7D))

**Comment by Krinkle** [comment]
I have confirmed that this passes on the specific Less.js version we aim to support (Less.js 2.5.3), e.g. via [fiddle](http://ecomfe.github.io/est/fiddle/#version=2.5.3&autoprefix=false&est=false&autorun=false).

```less
@position: after;

.foo {
    &:@{position} {
        color: green;
    }
}
```

Which Less.js 2.5.3 compiles to:

```css
.foo:after {
  color: green;
}
```
