### ISSUE TITLE
Uncaught Less Exception after moving from Leafo

### ISSUE THREAD

**Issue by moseleyi** [wikimedia/less.php#65]
I installed this version of the Less.php but I'm still getting errors like the following: 

```
Uncaught Less_Exception_Chunk: ParseError: Unexpected input in functions.less on line 76, column 13
74| font-size:@min_font + px;
75| @media(min-width: @min_vw + px){
76| font-size:~'calc(' + @min_font + 'px + (' + @max_font + ' - ' + @min_font + ') * ((100vw - ' + @min_vw + 'px) / (' + @max_vw + ' - ' + @min_vw + ')))';
77| }
78| @media(min-width: @max_vw + px){
79| font-size: @max_font + px;
in...
```

Is there a set of rules of what needs to be changed in code that worked with leafo, upon migration to this version?

**Comment by Krinkle** [comment]
@moseleyi I'm not sure how this worked in Leafo's parser, but what can say that the objective of Less.php is to match the behaviour of Less.js, and your example fails in a similar way in the official Less.js parser.

For example:

<http://ecomfe.github.io/est/fiddle/#version=3.8.1&autoprefix=false&est=false&autorun=false>

```less
@min_font: 10;
@max_font: 12;
@min_vw: 100;
@max_vw: 200;

.foo {
	font-size: @min_font + px;
	@media (min-width: @min_vw + px){
		font-size:~'calc(' + @min_font + 'px + (' + @max_font + ' - ' + @min_font + ') * ((100vw - ' + @min_vw + 'px) / (' + @max_vw + ' - ' + @min_vw + ')))';
	}
}
```
```
Syntax error: media definitions require block statements after any features
Line 9: 		font-size:~'calc(' + @min_font + 'px + (' + @max_font + ' - ' + @min_font + ') * ((100vw - ' + @min_vw + 'px) / (' + @max_vw + ' - ' + @min_vw + ')))';
```


The standard Less syntax for interpolating variables inside strings is `@{variable}`, and the syntax for escaping CSS code from strings is `~'text'`:

* https://lesscss.org/#escaping
* https://lesscss.org/features/#variables-feature-variable-interpolation

My guess is that Leafo's parser tolerated unquoted tokens like `px` but Less.js and Less.php do not. You can write your example as follows instead official Less syntax:

```less
@min_font: 10;
@max_font: 12;
@min_vw: 100;
@max_vw: 200;

.foo {
	font-size: @min_font + px;
    @media (min-width: ~"@{min_vw}px") {
        font-size: ~"calc(@{min_font}px + (@{max_font} - @{min_font}) * ((100vw - @{min_vw}px) / (@{max_vw} - @{min_vw})))";
	}
}

```

Output:
```css
.foo {
  font-size: 10 px;
}
@media (min-width: 100px) {
  .foo2 {
    font-size: calc(10px + (12 - 10) * ((100vw - 100px) / (200 - 100)));
  }
}
```
