### ISSUE TITLE
Error: array_merge() arg #2 must be array | calc(2rem + 4rem * var(--rockfrontend-grow));

### ISSUE THREAD

**Issue by BernhardBaumrock** [wikimedia/less.php#83]
I want to use this code:

```less
h2 {
  font-size: calc(2rem + 4rem * var(--rockfrontend-grow));
}
```

But unfortunately I get this error:
<img src=https://i.imgur.com/HLL0PJH.png>

Any ideas how to fix this?

**Comment by Gappa** [comment]
Escape the math functions:

``` less
h2 {
    font-size: calc(2rem ~"+" 4rem ~"*" var(--rockfrontend-grow));
}
```

All of them, don't let LESS try to compute any of that stuff :)
