### ISSUE TITLE
Cannot assign em or rem value to less variable.

### ISSUE THREAD

**Issue by jimlahm** [wikimedia/less.php#90]
I have a variable of the form:
 @h1-font-size: 2.25rem; 
which generates a fatal error in the less compiler. If I use 2.25em that also fails. Changing it to 36px works fine.

**Comment by Krinkle** [comment]
I'm not able to reproduce this issue.

```less
@h1-font-size: 2.25rem;

div {
  font-size: @h1-font-size;
}
```
```
less.php$ bin/lessc input.less
```
```css
div {
  font-size: 2.25rem;
}
```

@jimlahm Could you confirm the version of less.php that you use, and whether it still happens when you reduce it down to the above? Perhaps it is triggered by something else in the same file. A reduced test case would be great!
