### ISSUE TITLE
Error in Compiling

### ISSUE THREAD

**Issue by Ramishscrapper** [wikimedia/less.php#96]
This is not compiling 

```less
@width: 960px;
.nav {
  width: @width / 3;
  color: #001 + #abc;
}
.body {
  width: 2 * @width / 3;
  font-family: "hel" + "vetica";
}
```

it give me this error

```css
fatal error: ParseError: Unexpected input in anonymous-file-0.less on line 8, column 16
.body {
  width: 2 * @width / 3;
  font-family: \"hel\" + \"vetica\";
}
```

also getting here in this

```less
.clearfix {
  display: block;
  zoom: 1;

  &:after {
    content: " ";
    display: block;
    font-size: 0;
    height: 0;
    clear: both;
    visibility: hidden;
  }
}
```

this is the error I get

```css
fatal error: ParseError: Unexpected input in anonymous-file-0.less on line 6, column 14 
   &:after {
     content: \" \";
     display: block;
     font-size: 0;
     height: 0;
```

this is how I used php

```php
try {
    $parser = new Less_Parser();
    $parser->parse($lessCode);
    return $parser->getCss();
  } catch (exception $e) {
    return "fatal error: " . $e->getMessage();
}
```

**Comment by Krinkle** [comment]
> This is not compiling
> 
> ```css-less
> @width: 960px;
> .nav {
>   width: @width / 3;
>   color: #001 + #abc;
> }
> .body {
>   width: 2 * @width / 3;
>   font-family: "hel" + "vetica";
> }
> ```
> 
> it give me this error
> 
> ```css
> fatal error: ParseError: Unexpected input in anonymous-file-0.less on line 8, column 16
> .body {
>   width: 2 * @width / 3;
>   font-family: \"hel\" + \"vetica\";
> }
> ```

That's right. This kind of string concatenation is not supported by the Less standard. If you try the reference implementation in JavaScript, we see much the same error:

* http://ecomfe.github.io/est/fiddle/#version=2.5.3&autoprefix=false&est=false&autorun=false (reference version Less.js 2.5.3, matching Less.php)
* http://ecomfe.github.io/est/fiddle/#version=3.8.1&autoprefix=false&est=false&autorun=false (latest)

Both give the same result:
```
Parse error: Unrecognised input
Line 8:   font-family: "hel" + "vetica";
```

I suggest using `e()` and/or `%()` instead. Refer to the docs at <https://lesscss.org/functions/#string-functions-e>.

Example:
```css-less
div {
  font-family: %("%s%s", "hel", "vetica");
  font-family: e(%("%s%s", "hel", "vetica"));
}
```
```css
div {
  font-family: "helvetica";
  font-family: helvetica;
}
```
