### ISSUE TITLE
Support CSS4 space-separated syntax for rgba() function (Less.js 3.8.1)

### ISSUE THREAD

**Issue by kingscott** [wikimedia/less.php#98]
Hi there, we're currently using less/php v3.1.0 and are seeing errors when trying to import standard CSS files into our pipeline that use the newer syntax for rgba such as:

```css
.test {
  color: rgba(0 0 0 0 / 89%);
}
```

Is there a plan to support this in a future version, as I see it's supported in Less.js? Thanks!
